title: DARWIN
description: DAzzling Realization of dWarf galaxies In the Next generation of cosmological hydrodynamic simulations
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jiniewon.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
#author: lorepirri
#image: /thumbnail-jumbo.png
#twitter:
#  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['collaboration', 'events', 'contact']

email: "fkdlzks1002@gmail.com"
logo: "darwin.png"
