# Setup
title:        Darwin-simulation distribution ver TEST
tagline:      This is not real — just for testing. PLZ don’t try to use this website.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       JINJW
  url:        http://jiniewon.github.io 

cayman-blog:
  date_format: "%b %-d, %Y"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

header_page_refs: ['collaboration', 'events', contact']

email: "fkdlzks1002@gmail.com"
#logo: "darwin.png"
